batch_size: 128
hid_dim: 256
lr: 0.003
#lr: 0.3
wd: !!float 1e-4
n_layers: 2
dropout: [0.2, 0.1]
device: "cpu"
#device: "cuda:0"
early_stopping: 10
#n_fold: 5
n_fold: 2
seed: 2023
#max_epochs: 15
max_epochs: 1
gated: True
#dataset: S-FFSD
dataset: yelp
#dataset: amazon
test_size: 0.4